### ISSUE TITLE
Creating Tasks

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer-react#10]
**Acceptance criteria**
- [x] Available to authenticated users only
- [x] Validation errors are displayed to the user
- [x] User can successfully create tasks

**Tasks**
- [x] Create a form for creating tasks
- [x] Create and Cancel buttons
- [x] function for sending the form to API
