### ISSUE TITLE
Updating Tasks

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer-react#11]
**Acceptance criteria**
- [x] Available to authenticated users only
- [x] Validation errors are displayed to the user
- [x] User can successfully update tasks

**Tasks**
- [x] Create a form for editing tasks
- [x] Save and Cancel buttons
- [x] function for sending the form to API via PUT-Method
