### ISSUE TITLE
Creating Teams

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer-react#12]
**Acceptance criteria**
- [x] Teams can be created by authenticated users only

**Tasks**
- [x] Create React Component for creating teams
- [x] function for posting the Form to API
- [x] Render input field for name of team
- [x] Create and Cancel buttons
