### ISSUE TITLE
Updating Teams

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer-react#13]
**Acceptance criteria**
- [x] Teams can be updated by owners only

**Tasks**
- [x] Create React Component for editing teams
- [x] function for sending the Form to API via PUT-Method
- [x] Render input field for name of team
- [x] Save and Cancel buttons
