### ISSUE TITLE
Team Chat Room

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer-react#14]
**Assessment criteria**
- [x] Leave a message for the team
- [x] Edit an existing message
- [x] Delete an existing message
- [x] View existing messages
- [x] Messages can only be edited or deleted by their owners
- [x] Users must be member of the team to view the messages

**Tasks**
- [x] Chat Room route
- [x] Chat Room Component
- [x] Bar with Filters Component
- [x] Message Board Component
- [x] Component for a single Message representation
- [x] Form for Posting new messages
- [x] Form for editing existing messages
