### ISSUE TITLE
Private Chat Room

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer-react#15]
**Assessment criteria**
- [x] User can send private messages to a team member
- [x] Users can attach images to their messages
- [x] User can edit existing messages
- [x] User can delete his or her own messages

**Tasks**
- [x] Create Private Message Board component
- [x] Create a Component for posting private messages
- [x] Create a Component for editing existing messages
- [x] Create a Component that renders a single message 
- [x] Add an edit button to the single message component if the user is the owner of the message
- [x] Add a delete button to the single message component if the user is the owner of the message
