### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer-react#3]
**Acceptance criteria**
- [x] Current month and year are visible to user
- [x] Navigation between months using buttons
- [x] User can see if any of the days of the given month has tasks in it
- [x] User can select one day
- [x] User can select an entire month
- [x] Calendar can communicate ,which day has been selected by the user, to its parent component
- [x] Calendar can communicate ,which month has been selected by the user , to its parent component

**Tasks**
- [x] React Component named Calendar
- [x] Correct presentation of a given month in a year(number of days in month, leap year, etc.)
- [x] Retrieving a list of Tasks for a given day from the API
- [x] Displaying some hint of existing tasks in the boxes with day numbers
- [x] Communication with the parent component
