### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer-react#4]
**Acceptance criteria**
- [x] Access tokens are available
- [x] Users can sign up or sign in
- [x] User is stored in the context and is available to other components

**Tasks**
- [x] Fetch user data from API and store it in the context
- [x] Copy the code snippet from code institute for axios.interceptors, to facilitate that access tokens are refreshed regularly
- [x] Provide Registration Form
- [x] Provide Login Form
