### ISSUE TITLE
Listing Tasks

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer-react#5]
**Acceptance criteria**
- [x] The search filter is hooked up with the Calendar Component
- [x] The list of tasks reflects user's selection in the Calendar component
- [x] User can use Filters (category, priority, status)
- [x] User can search tasks by title
- [x] The list maps the data from API to instances of the Component for displaying individual tasks

**Tasks**
- [x] Function for retrieving a task list for the Calendar component
- [x] Render the Calendar Component
- [x] Render a Search Field
- [x] Render a list of applicable filters
- [x] Render a task list for the month or date that was selected in the Calendar Component
- [x] Order the task list by date in the ascending order
