### ISSUE TITLE
Individual Tasks

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer-react#6]
**Acceptance criteria**
- [x] Attributes such as title, comment, time, date, etc.. are displayed
- [x] Attached pictures can be viewed by users in a separate Tab
- [x] Edit and Delete Buttons are available
- [x] User is prompted to confirm delete before the Task is deleted
- [x] Click on Edit button  opens a form for updating the task

**Tasks**
- [x] Create Component that can be initialized with data that reflects a Task object
- [x] Render the Task properties
- [x] Add Edit button with a link to the corresponding page
- [x] Add Delete button
- [x] Define a delete function
- [x] Display a confirm dialog before deleting
