### ISSUE TITLE
Listing Teams

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer-react#7]
**Acceptance criteria**
- [x] Requests to API work
- [x] Teams can be searched by username
- [x] Teams can be searched by team name

**Tasks**
- [x] Create Component listing team
- [x] function for retrieving a list of teams
- [x] Select fields for filters category, priority and status
- [x] Search bar
