### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer-react#8]
**Acceptance criteria**
- [x] A set of Links for unauthenticated users
- [x] A set of Links for authenticated users

**Tasks**
- [x] Create Navigation Bar Component
- [x] Link to Sign-in form
- [x] Linkt to Sign-out form
- [x] Link to Sign-up form
- [x] Link to a form for creating new Tasks
- [x] Link to a form for creating new Teams
