### ISSUE TITLE
Individual Teams

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer-react#9]
**Acceptance criteria**
- [x] Properties passed down by the parent are rendered correctly
- [x] Team can be deleted by its owner
- [x] Owner can open the team for editing
- [x] Users, who are not owners of the team, can join the team
- [x] Users, who are members of the team, can quit the team

**Tasks**
- [x] Create Team Component that accepts a set of properties from its parent
- [x] Render the properties
- [x] Delete and Edit button for the owner of the team
- [x] Join button for authenticated users who are not the owner of the team
- [x] Leave button for members of the team
- [x] functions that facilitate deleting, editing, joining, leaving the team
